<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DocumentEvidence.Api.Contracts/DocumentEvidence.Api.Contracts.csproj" />
    <ProjectReference Include="../../src/DocumentEvidence.Client/DocumentEvidence.Client.csproj" />
  </ItemGroup>
</Project>
