// <auto-generated />
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using KnowledgePilot.LogicLens.DocumentEvidence.Api.Contracts;

namespace KnowledgePilot.LogicLens.DocumentEvidence.Client;

internal sealed class DocumentEvidenceClientTransport
{
    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    private readonly HttpClient _httpClient;

    public DocumentEvidenceClientTransport(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<T> SendAsync<T>(
        HttpRequestMessage request,
        HttpStatusCode expectedStatus,
        CancellationToken cancellationToken
    )
    {
        using var response = await _httpClient.SendAsync(
            request,
            HttpCompletionOption.ResponseHeadersRead,
            cancellationToken
        );
        if (response.StatusCode != expectedStatus)
        {
            await ThrowFailureAsync(response, cancellationToken);
        }
        var value = await response.Content.ReadFromJsonAsync<T>(Json, cancellationToken);
        return value ?? throw new InvalidDataException(
            "Document Evidence Service returned an empty JSON response."
        );
    }

    public async Task<T?> SendOptionalAsync<T>(
        HttpRequestMessage request,
        CancellationToken cancellationToken
    )
    {
        using var response = await _httpClient.SendAsync(
            request,
            HttpCompletionOption.ResponseHeadersRead,
            cancellationToken
        );
        if (response.StatusCode == HttpStatusCode.NotFound)
        {
            return default;
        }
        if (response.StatusCode != HttpStatusCode.OK)
        {
            await ThrowFailureAsync(response, cancellationToken);
        }
        return await response.Content.ReadFromJsonAsync<T>(Json, cancellationToken);
    }

    private static async Task ThrowFailureAsync(
        HttpResponseMessage response,
        CancellationToken cancellationToken
    )
    {
        DocumentEvidenceErrorDto? error = null;
        try
        {
            error = await response.Content.ReadFromJsonAsync<DocumentEvidenceErrorDto>(
                Json,
                cancellationToken
            );
        }
        catch (JsonException)
        {
        }
        throw new DocumentEvidenceClientException(
            response.StatusCode,
            error?.Code ?? "http-error",
            error?.Message ?? $"Document Evidence Service returned HTTP {(int)response.StatusCode}.",
            error?.Retryable ?? false
        );
    }
}
