// <auto-generated />
using System.Net;
using System.Net.Http.Headers;
using KnowledgePilot.LogicLens.DocumentEvidence.Api.Contracts;

namespace KnowledgePilot.LogicLens.DocumentEvidence.Client;

public sealed class DocumentEvidenceClient
{
    private readonly Guid _actorId;
    private readonly DocumentEvidenceClientTransport _transport;

    public DocumentEvidenceClient(HttpClient httpClient, Guid actorId)
    {
        ArgumentNullException.ThrowIfNull(httpClient);
        if (actorId == Guid.Empty)
        {
            throw new ArgumentException("Actor ID must be a non-empty GUID.", nameof(actorId));
        }
        _actorId = actorId;
        _transport = new DocumentEvidenceClientTransport(httpClient);
    }

    public async Task<UploadRevisionDto> UploadRevisionAsync(
        Guid workspaceId,
        Guid documentId,
        string displayName,
        string idempotencyKey,
        string mediaType,
        Stream content,
        long? contentLength = null,
        string sourceKind = "Upload",
        CancellationToken cancellationToken = default
    )
    {
        using var request = CreateRequest(
            HttpMethod.Put,
            DocumentEvidenceApiV1.UploadRevision(workspaceId, documentId)
        );
        request.Headers.TryAddWithoutValidation(
            DocumentEvidenceApiV1.FileNameHeader,
            displayName
        );
        request.Headers.TryAddWithoutValidation(
            DocumentEvidenceApiV1.IdempotencyHeader,
            idempotencyKey
        );
        request.Headers.TryAddWithoutValidation(
            DocumentEvidenceApiV1.SourceKindHeader,
            sourceKind
        );
        request.Content = new StreamContent(content);
        request.Content.Headers.ContentType = MediaTypeHeaderValue.Parse(mediaType);
        request.Content.Headers.ContentLength = contentLength;
        return await _transport.SendAsync<UploadRevisionDto>(
            request,
            HttpStatusCode.Created,
            cancellationToken
        );
    }

    public Task<DocumentMetadataDto?> GetDocumentAsync(
        Guid workspaceId,
        Guid documentId,
        CancellationToken cancellationToken = default
    )
    {
        var request = CreateRequest(
            HttpMethod.Get,
            DocumentEvidenceApiV1.Document(workspaceId, documentId)
        );
        return _transport.SendOptionalAsync<DocumentMetadataDto>(request, cancellationToken);
    }

    public Task<IReadOnlyList<DocumentFragmentDto>> ListFragmentsAsync(
        Guid workspaceId,
        Guid revisionId,
        CancellationToken cancellationToken = default
    )
    {
        var request = CreateRequest(
            HttpMethod.Get,
            DocumentEvidenceApiV1.Fragments(workspaceId, revisionId)
        );
        return _transport.SendAsync<IReadOnlyList<DocumentFragmentDto>>(
            request,
            HttpStatusCode.OK,
            cancellationToken
        );
    }

    private HttpRequestMessage CreateRequest(HttpMethod method, string relativeUrl)
    {
        var request = new HttpRequestMessage(method, relativeUrl);
        request.Headers.TryAddWithoutValidation(
            DocumentEvidenceApiV1.ActorHeader,
            _actorId.ToString("D")
        );
        return request;
    }
}
