using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using LogicLens.Prolog.Serialization;

namespace LogicLens.OntologyCompiler;

internal sealed record OntologyPackage(
    string GeneratedContent,
    string GeneratedSha256,
    string PackageHash,
    string ManifestJson,
    int TermCount,
    int LabelCount,
    int PriorityCount);

internal sealed class OntologyPrologWriter
{
    private const string GeneratedPath = "ontology.generated.pl";
    private static readonly UTF8Encoding Utf8WithoutBom = new(false);

    public OntologyPackage Build(
        OntologySnapshot snapshot,
        string compilerCommit)
    {
        ArgumentNullException.ThrowIfNull(snapshot);
        if (string.IsNullOrWhiteSpace(compilerCommit))
        {
            throw new ArgumentException(
                "Compiler commit cannot be null, empty, or whitespace.",
                nameof(compilerCommit));
        }

        var content = BuildGeneratedContent(snapshot);
        var contentBytes = Utf8WithoutBom.GetBytes(content);
        var generatedSha = Sha256(contentBytes);
        var packageHash = ComputePackageHash(contentBytes);
        var priorityCount = snapshot.Terms.Count(static term => term.Priority is not null);
        var manifest = BuildManifest(
            snapshot,
            compilerCommit,
            generatedSha,
            packageHash,
            priorityCount);

        return new OntologyPackage(
            content,
            generatedSha,
            packageHash,
            manifest,
            snapshot.Terms.Count,
            snapshot.LabelCount,
            priorityCount);
    }

    public void WriteToDirectory(OntologyPackage package, string outputDirectory)
    {
        ArgumentNullException.ThrowIfNull(package);
        if (string.IsNullOrWhiteSpace(outputDirectory))
        {
            throw new ArgumentException(
                "Output directory cannot be null, empty, or whitespace.",
                nameof(outputDirectory));
        }

        Directory.CreateDirectory(outputDirectory);
        File.WriteAllText(
            Path.Combine(outputDirectory, GeneratedPath),
            package.GeneratedContent,
            Utf8WithoutBom);
        File.WriteAllText(
            Path.Combine(outputDirectory, "manifest.json"),
            package.ManifestJson,
            Utf8WithoutBom);
    }

    private static string BuildGeneratedContent(OntologySnapshot snapshot)
    {
        var builder = new StringBuilder();
        builder.AppendLine("% Generated by LogicLens ontology label contract v1. Do not edit.");

        foreach (var term in snapshot.Terms)
        {
            builder
                .Append("ontology_term(")
                .Append(PrologText.Atom(term.Id)).Append(", ")
                .Append(RenderKind(term.Kind))
                .AppendLine(").");
        }

        builder.AppendLine();

        foreach (var label in snapshot.Terms
                     .SelectMany(static term => term.Labels.Select(value =>
                         (term.Id, Label: value)))
                     .OrderBy(static item => item.Id, StringComparer.Ordinal)
                     .ThenBy(static item => item.Label.Direction)
                     .ThenBy(static item => item.Label.Language, StringComparer.Ordinal)
                     .ThenBy(static item => item.Label.Text, StringComparer.Ordinal))
        {
            builder
                .Append("ontology_label(")
                .Append(PrologText.Atom(label.Id)).Append(", ")
                .Append(RenderDirection(label.Label.Direction)).Append(", ")
                .Append(PrologText.Atom(label.Label.Language)).Append(", ")
                .Append(PrologText.String(label.Label.Text))
                .AppendLine(").");
        }

        builder.AppendLine();

        foreach (var term in snapshot.Terms
                     .Where(static term => term.Priority is not null)
                     .OrderBy(static term => term.Id, StringComparer.Ordinal))
        {
            builder
                .Append("ontology_priority(")
                .Append(PrologText.Atom(term.Id)).Append(", ")
                .Append(PrologText.String(term.Priority!))
                .AppendLine(").");
        }

        return builder.ToString().TrimEnd('\r', '\n') + "\n";
    }

    private static string BuildManifest(
        OntologySnapshot snapshot,
        string compilerCommit,
        string generatedSha,
        string packageHash,
        int priorityCount)
    {
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream, new JsonWriterOptions
               {
                   Indented = true
               }))
        {
            writer.WriteStartObject();
            writer.WriteString("stage", "ontology-generated");
            writer.WriteString("ontologyLabelContractVersion", "1");
            writer.WriteString("compilerCommit", compilerCommit);
            writer.WriteString("sourcePath", snapshot.SourcePath);
            writer.WriteString("sourceDbId", snapshot.SourceDbId);
            writer.WriteNumber("termCount", snapshot.Terms.Count);
            writer.WriteNumber("labelCount", snapshot.LabelCount);
            writer.WriteNumber("priorityCount", priorityCount);
            writer.WriteStartObject("files");
            writer.WriteString(GeneratedPath, generatedSha);
            writer.WriteEndObject();
            writer.WriteString("packageHash", packageHash);
            writer.WriteEndObject();
        }

        return Utf8WithoutBom.GetString(stream.ToArray()) + "\n";
    }

    private static string ComputePackageHash(byte[] generatedContent)
    {
        using var hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
        hash.AppendData(Encoding.ASCII.GetBytes("LogicLensOntologyLabels\0"));
        hash.AppendData([0x01]);
        AppendField(hash, Encoding.UTF8.GetBytes(GeneratedPath));
        AppendField(hash, generatedContent);
        return "sha256:" + Convert.ToHexString(hash.GetHashAndReset()).ToLowerInvariant();
    }

    private static void AppendField(IncrementalHash hash, byte[] bytes)
    {
        Span<byte> length = stackalloc byte[sizeof(ulong)];
        BinaryPrimitives.WriteUInt64BigEndian(length, checked((ulong)bytes.Length));
        hash.AppendData(length);
        hash.AppendData(bytes);
    }

    private static string RenderKind(OntologyTermKind kind) => kind switch
    {
        OntologyTermKind.Class => "class",
        OntologyTermKind.DatatypeProperty => "datatype_property",
        OntologyTermKind.ObjectProperty => "object_property",
        OntologyTermKind.EnumerationType => "enumeration_type",
        _ => throw new ArgumentOutOfRangeException(nameof(kind), kind, null)
    };

    private static string RenderDirection(OntologyLabelDirection direction) => direction switch
    {
        OntologyLabelDirection.Forward => "forward",
        OntologyLabelDirection.Inverse => "inverse",
        _ => throw new ArgumentOutOfRangeException(nameof(direction), direction, null)
    };

    private static string Sha256(byte[] bytes) =>
        "sha256:" + Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
}
