% Generated by LogicLens ontology label contract v1. Do not edit.
ontology_term('http://fogid.net/o/DocumentPart', class).
ontology_term('http://fogid.net/o/adoc', object_property).
ontology_term('http://fogid.net/o/alias', datatype_property).
ontology_term('http://fogid.net/o/archive', class).
ontology_term('http://fogid.net/o/archive-item', object_property).
ontology_term('http://fogid.net/o/archive-member', class).
ontology_term('http://fogid.net/o/aspirant', class).
ontology_term('http://fogid.net/o/at-meeting', object_property).
ontology_term('http://fogid.net/o/audio-doc', class).
ontology_term('http://fogid.net/o/author', object_property).
ontology_term('http://fogid.net/o/authority', class).
ontology_term('http://fogid.net/o/authority-specificator', datatype_property).
ontology_term('http://fogid.net/o/authority-variants', enumeration_type).
ontology_term('http://fogid.net/o/business', datatype_property).
ontology_term('http://fogid.net/o/business-activity', class).
ontology_term('http://fogid.net/o/cassette', class).
ontology_term('http://fogid.net/o/city', class).
ontology_term('http://fogid.net/o/code', datatype_property).
ontology_term('http://fogid.net/o/collection', class).
ontology_term('http://fogid.net/o/collection-item', object_property).
ontology_term('http://fogid.net/o/collection-member', class).
ontology_term('http://fogid.net/o/comment', datatype_property).
ontology_term('http://fogid.net/o/communication', class).
ontology_term('http://fogid.net/o/concernment', datatype_property).
ontology_term('http://fogid.net/o/country', class).
ontology_term('http://fogid.net/o/date', datatype_property).
ontology_term('http://fogid.net/o/dating', class).
ontology_term('http://fogid.net/o/dating-accuracy', datatype_property).
ontology_term('http://fogid.net/o/dating-specificator', datatype_property).
ontology_term('http://fogid.net/o/dating-variants', enumeration_type).
ontology_term('http://fogid.net/o/degree', datatype_property).
ontology_term('http://fogid.net/o/description', datatype_property).
ontology_term('http://fogid.net/o/doc-content', datatype_property).
ontology_term('http://fogid.net/o/docmetainfo', datatype_property).
ontology_term('http://fogid.net/o/document', class).
ontology_term('http://fogid.net/o/entity', class).
ontology_term('http://fogid.net/o/family', class).
ontology_term('http://fogid.net/o/father', object_property).
ontology_term('http://fogid.net/o/from-date', datatype_property).
ontology_term('http://fogid.net/o/geosys', class).
ontology_term('http://fogid.net/o/geosys-category', datatype_property).
ontology_term('http://fogid.net/o/geosys-special', class).
ontology_term('http://fogid.net/o/ground', datatype_property).
ontology_term('http://fogid.net/o/has-activity', object_property).
ontology_term('http://fogid.net/o/has-title', object_property).
ontology_term('http://fogid.net/o/husband', object_property).
ontology_term('http://fogid.net/o/in-archive', object_property).
ontology_term('http://fogid.net/o/in-collection', object_property).
ontology_term('http://fogid.net/o/in-doc', object_property).
ontology_term('http://fogid.net/o/in-org', object_property).
ontology_term('http://fogid.net/o/inDocument', object_property).
ontology_term('http://fogid.net/o/info-source', object_property).
ontology_term('http://fogid.net/o/learn', class).
ontology_term('http://fogid.net/o/learn-category', datatype_property).
ontology_term('http://fogid.net/o/learn-special', class).
ontology_term('http://fogid.net/o/learner', object_property).
ontology_term('http://fogid.net/o/learning-org', object_property).
ontology_term('http://fogid.net/o/location', class).
ontology_term('http://fogid.net/o/location-category', datatype_property).
ontology_term('http://fogid.net/o/location-classification', datatype_property).
ontology_term('http://fogid.net/o/location-classificator', enumeration_type).
ontology_term('http://fogid.net/o/location-place', object_property).
ontology_term('http://fogid.net/o/mother', object_property).
ontology_term('http://fogid.net/o/name', datatype_property).
ontology_term('http://fogid.net/o/naming', class).
ontology_term('http://fogid.net/o/org-category', datatype_property).
ontology_term('http://fogid.net/o/org-child', object_property).
ontology_term('http://fogid.net/o/org-classification', datatype_property).
ontology_term('http://fogid.net/o/org-classificator', enumeration_type).
ontology_term('http://fogid.net/o/org-parent', object_property).
ontology_term('http://fogid.net/o/org-relatives', class).
ontology_term('http://fogid.net/o/org-sys', class).
ontology_term('http://fogid.net/o/pageNumbers', datatype_property).
ontology_term('http://fogid.net/o/partItem', object_property).
ontology_term('http://fogid.net/o/participant', object_property).
ontology_term('http://fogid.net/o/participation', class).
ontology_term('http://fogid.net/o/person', class).
ontology_term('http://fogid.net/o/person-sex', enumeration_type).
ontology_term('http://fogid.net/o/personage-ground', enumeration_type).
ontology_term('http://fogid.net/o/photo-doc', class).
ontology_term('http://fogid.net/o/pupil', class).
ontology_term('http://fogid.net/o/referred', object_property).
ontology_term('http://fogid.net/o/referred-sys', object_property).
ontology_term('http://fogid.net/o/reflected', object_property).
ontology_term('http://fogid.net/o/reflection', class).
ontology_term('http://fogid.net/o/region', class).
ontology_term('http://fogid.net/o/role', datatype_property).
ontology_term('http://fogid.net/o/role-classification', datatype_property).
ontology_term('http://fogid.net/o/role-classificator', enumeration_type).
ontology_term('http://fogid.net/o/sex', datatype_property).
ontology_term('http://fogid.net/o/something', object_property).
ontology_term('http://fogid.net/o/speech', class).
ontology_term('http://fogid.net/o/student', class).
ontology_term('http://fogid.net/o/support-org', object_property).
ontology_term('http://fogid.net/o/sys-obj', class).
ontology_term('http://fogid.net/o/titled', class).
ontology_term('http://fogid.net/o/to-date', datatype_property).
ontology_term('http://fogid.net/o/uri', datatype_property).
ontology_term('http://fogid.net/o/user', object_property).
ontology_term('http://fogid.net/o/video-doc', class).
ontology_term('http://fogid.net/o/wife', object_property).

ontology_label('http://fogid.net/o/DocumentPart', forward, 'en', "Part of document").
ontology_label('http://fogid.net/o/DocumentPart', forward, 'ru', "Раздел документа").
ontology_label('http://fogid.net/o/adoc', forward, 'en', "document").
ontology_label('http://fogid.net/o/adoc', forward, 'ru', "документ").
ontology_label('http://fogid.net/o/adoc', inverse, 'en', "subject").
ontology_label('http://fogid.net/o/adoc', inverse, 'ru', "субъект").
ontology_label('http://fogid.net/o/alias', forward, 'en', "another name").
ontology_label('http://fogid.net/o/alias', forward, 'ru', "друг. имя").
ontology_label('http://fogid.net/o/archive', forward, 'en', "Archive").
ontology_label('http://fogid.net/o/archive', forward, 'ru', "Архив").
ontology_label('http://fogid.net/o/archive-item', forward, 'en', "contains").
ontology_label('http://fogid.net/o/archive-item', forward, 'ru', "содержит").
ontology_label('http://fogid.net/o/archive-item', inverse, 'en', "element for").
ontology_label('http://fogid.net/o/archive-item', inverse, 'ru', "элемент архива").
ontology_label('http://fogid.net/o/archive-member', forward, 'en', "Archive's element").
ontology_label('http://fogid.net/o/archive-member', forward, 'ru', "Элемент архива").
ontology_label('http://fogid.net/o/aspirant', forward, 'en', "Graduate student").
ontology_label('http://fogid.net/o/aspirant', forward, 'ru', "Аспирант").
ontology_label('http://fogid.net/o/at-meeting', forward, 'en', "at meeting").
ontology_label('http://fogid.net/o/at-meeting', forward, 'ru', "на встрече в").
ontology_label('http://fogid.net/o/at-meeting', inverse, 'en', "speech").
ontology_label('http://fogid.net/o/at-meeting', inverse, 'ru', "выступление").
ontology_label('http://fogid.net/o/audio-doc', forward, 'en', "Audio document").
ontology_label('http://fogid.net/o/audio-doc', forward, 'ru', "Аудиодокумент").
ontology_label('http://fogid.net/o/author', forward, 'en', "sender/receiver").
ontology_label('http://fogid.net/o/author', forward, 'ru', "автор/получатель").
ontology_label('http://fogid.net/o/author', inverse, 'en', "document in/out person/org").
ontology_label('http://fogid.net/o/author', inverse, 'ru', "субъект документа").
ontology_label('http://fogid.net/o/authority', forward, 'en', "Authority").
ontology_label('http://fogid.net/o/authority', forward, 'ru', "Полномочия").
ontology_label('http://fogid.net/o/authority-specificator', forward, 'en', "authority specificator").
ontology_label('http://fogid.net/o/authority-specificator', forward, 'ru', "спецификатор полномочий").
ontology_label('http://fogid.net/o/business', forward, 'en', "activity").
ontology_label('http://fogid.net/o/business', forward, 'ru', "деятельность").
ontology_label('http://fogid.net/o/business-activity', forward, 'en', "Field of activity").
ontology_label('http://fogid.net/o/business-activity', forward, 'ru', "Сфера деятельности").
ontology_label('http://fogid.net/o/cassette', forward, 'en', "Cassette").
ontology_label('http://fogid.net/o/cassette', forward, 'ru', "Кассета").
ontology_label('http://fogid.net/o/city', forward, 'en', "City").
ontology_label('http://fogid.net/o/city', forward, 'ru', "Город").
ontology_label('http://fogid.net/o/code', forward, 'en', "code").
ontology_label('http://fogid.net/o/code', forward, 'ru', "номер/код").
ontology_label('http://fogid.net/o/collection', forward, 'en', "Collection").
ontology_label('http://fogid.net/o/collection', forward, 'ru', "Коллекция").
ontology_label('http://fogid.net/o/collection-item', forward, 'en', "contains").
ontology_label('http://fogid.net/o/collection-item', forward, 'ru', "содержит").
ontology_label('http://fogid.net/o/collection-item', inverse, 'en', "collection's element").
ontology_label('http://fogid.net/o/collection-item', inverse, 'ru', "элемент коллекции").
ontology_label('http://fogid.net/o/collection-member', forward, 'en', "Collection's element").
ontology_label('http://fogid.net/o/collection-member', forward, 'ru', "Элемент коллекции").
ontology_label('http://fogid.net/o/comment', forward, 'en', "comment").
ontology_label('http://fogid.net/o/comment', forward, 'ru', "комментарий").
ontology_label('http://fogid.net/o/concernment', forward, 'en', "importance").
ontology_label('http://fogid.net/o/concernment', forward, 'ru', "значимость").
ontology_label('http://fogid.net/o/country', forward, 'en', "Country").
ontology_label('http://fogid.net/o/country', forward, 'ru', "Страна").
ontology_label('http://fogid.net/o/date', forward, 'en', "date").
ontology_label('http://fogid.net/o/date', forward, 'ru', "дата").
ontology_label('http://fogid.net/o/dating', forward, 'en', "Dating").
ontology_label('http://fogid.net/o/dating', forward, 'ru', "Датирование").
ontology_label('http://fogid.net/o/dating-accuracy', forward, 'en', "dating accuracy").
ontology_label('http://fogid.net/o/dating-accuracy', forward, 'ru', "точность датирования").
ontology_label('http://fogid.net/o/dating-specificator', forward, 'en', "dating specifier").
ontology_label('http://fogid.net/o/dating-specificator', forward, 'ru', "спецификатор датирования").
ontology_label('http://fogid.net/o/degree', forward, 'en', "degree").
ontology_label('http://fogid.net/o/degree', forward, 'ru', "степень").
ontology_label('http://fogid.net/o/description', forward, 'en', "description").
ontology_label('http://fogid.net/o/description', forward, 'ru', "описание").
ontology_label('http://fogid.net/o/doc-content', forward, 'en', "document text").
ontology_label('http://fogid.net/o/doc-content', forward, 'ru', "текст документа").
ontology_label('http://fogid.net/o/docmetainfo', forward, 'en', "meta info").
ontology_label('http://fogid.net/o/docmetainfo', forward, 'ru', "метаинформ.").
ontology_label('http://fogid.net/o/document', forward, 'en', "Document").
ontology_label('http://fogid.net/o/document', forward, 'ru', "Документ").
ontology_label('http://fogid.net/o/family', forward, 'en', "Family").
ontology_label('http://fogid.net/o/family', forward, 'ru', "Семья").
ontology_label('http://fogid.net/o/father', forward, 'en', "father").
ontology_label('http://fogid.net/o/father', forward, 'ru', "отец").
ontology_label('http://fogid.net/o/father', inverse, 'en', "child").
ontology_label('http://fogid.net/o/father', inverse, 'ru', "ребенок").
ontology_label('http://fogid.net/o/from-date', forward, 'en', "initial date").
ontology_label('http://fogid.net/o/from-date', forward, 'ru', "нач.дата").
ontology_label('http://fogid.net/o/geosys', forward, 'en', "Geosystem").
ontology_label('http://fogid.net/o/geosys', forward, 'ru', "Геосистема").
ontology_label('http://fogid.net/o/geosys-category', forward, 'en', "geosystem category").
ontology_label('http://fogid.net/o/geosys-category', forward, 'ru', "категория геосистемы").
ontology_label('http://fogid.net/o/geosys-special', forward, 'en', "Geosystem special").
ontology_label('http://fogid.net/o/geosys-special', forward, 'ru', "Геосистема специальная").
ontology_label('http://fogid.net/o/ground', forward, 'en', "ground").
ontology_label('http://fogid.net/o/ground', forward, 'ru', "план").
ontology_label('http://fogid.net/o/has-activity', forward, 'en', "subject").
ontology_label('http://fogid.net/o/has-activity', forward, 'ru', "субъект").
ontology_label('http://fogid.net/o/has-activity', inverse, 'en', "specialist in").
ontology_label('http://fogid.net/o/has-activity', inverse, 'ru', "специалист в").
ontology_label('http://fogid.net/o/has-title', forward, 'en', "subject").
ontology_label('http://fogid.net/o/has-title', forward, 'ru', "субъект").
ontology_label('http://fogid.net/o/has-title', inverse, 'en', "degree/title").
ontology_label('http://fogid.net/o/has-title', inverse, 'ru', "степень/титул").
ontology_label('http://fogid.net/o/husband', forward, 'en', "husband").
ontology_label('http://fogid.net/o/husband', forward, 'ru', "муж").
ontology_label('http://fogid.net/o/husband', inverse, 'en', "husband for").
ontology_label('http://fogid.net/o/husband', inverse, 'ru', "муж для").
ontology_label('http://fogid.net/o/in-archive', forward, 'en', "in archive").
ontology_label('http://fogid.net/o/in-archive', forward, 'ru', "в архиве").
ontology_label('http://fogid.net/o/in-archive', inverse, 'en', "archive for").
ontology_label('http://fogid.net/o/in-archive', inverse, 'ru', "архив для").
ontology_label('http://fogid.net/o/in-collection', forward, 'en', "in collection").
ontology_label('http://fogid.net/o/in-collection', forward, 'ru', "в коллекции").
ontology_label('http://fogid.net/o/in-collection', inverse, 'en', "collection for").
ontology_label('http://fogid.net/o/in-collection', inverse, 'ru', "коллекция для").
ontology_label('http://fogid.net/o/in-doc', forward, 'en', "in document").
ontology_label('http://fogid.net/o/in-doc', forward, 'ru', "в документе").
ontology_label('http://fogid.net/o/in-doc', inverse, 'en', "reflected personage").
ontology_label('http://fogid.net/o/in-doc', inverse, 'ru', "отраж. персонаж").
ontology_label('http://fogid.net/o/in-org', forward, 'en', "in organization system").
ontology_label('http://fogid.net/o/in-org', forward, 'ru', "в орг. сист.").
ontology_label('http://fogid.net/o/in-org', inverse, 'en', "worker/participant").
ontology_label('http://fogid.net/o/in-org', inverse, 'ru', "работник/участник").
ontology_label('http://fogid.net/o/inDocument', forward, 'en', "in document").
ontology_label('http://fogid.net/o/inDocument', forward, 'ru', "в сборке").
ontology_label('http://fogid.net/o/inDocument', inverse, 'en', "parts").
ontology_label('http://fogid.net/o/inDocument', inverse, 'ru', "разделы").
ontology_label('http://fogid.net/o/info-source', forward, 'en', "information source").
ontology_label('http://fogid.net/o/info-source', forward, 'ru', "источник инф.").
ontology_label('http://fogid.net/o/info-source', inverse, 'en', "information source for").
ontology_label('http://fogid.net/o/info-source', inverse, 'ru', "источник инф. для").
ontology_label('http://fogid.net/o/learn', forward, 'en', "Education").
ontology_label('http://fogid.net/o/learn', forward, 'ru', "Учеба").
ontology_label('http://fogid.net/o/learn-category', forward, 'en', "education type").
ontology_label('http://fogid.net/o/learn-category', forward, 'ru', "тип обучения").
ontology_label('http://fogid.net/o/learn-special', forward, 'en', "Education special").
ontology_label('http://fogid.net/o/learn-special', forward, 'ru', "Учеба спец.").
ontology_label('http://fogid.net/o/learner', forward, 'en', "pupil").
ontology_label('http://fogid.net/o/learner', forward, 'ru', "ученик").
ontology_label('http://fogid.net/o/learner', inverse, 'en', "education in").
ontology_label('http://fogid.net/o/learner', inverse, 'ru', "образование в").
ontology_label('http://fogid.net/o/learning-org', forward, 'en', "in educational organization").
ontology_label('http://fogid.net/o/learning-org', forward, 'ru', "в уч. заведении").
ontology_label('http://fogid.net/o/learning-org', inverse, 'en', "learner").
ontology_label('http://fogid.net/o/learning-org', inverse, 'ru', "учащийся").
ontology_label('http://fogid.net/o/location', forward, 'en', "Location").
ontology_label('http://fogid.net/o/location', forward, 'ru', "Расположение").
ontology_label('http://fogid.net/o/location-category', forward, 'en', "location type").
ontology_label('http://fogid.net/o/location-category', forward, 'ru', "тип размещения").
ontology_label('http://fogid.net/o/location-classification', forward, 'en', "location classifier").
ontology_label('http://fogid.net/o/location-classification', forward, 'ru', "клсф.размещ.").
ontology_label('http://fogid.net/o/location-place', forward, 'en', "place").
ontology_label('http://fogid.net/o/location-place', forward, 'ru', "место").
ontology_label('http://fogid.net/o/location-place', inverse, 'en', "place for").
ontology_label('http://fogid.net/o/location-place', inverse, 'ru', "место для").
ontology_label('http://fogid.net/o/mother', forward, 'en', "mother").
ontology_label('http://fogid.net/o/mother', forward, 'ru', "мать").
ontology_label('http://fogid.net/o/mother', inverse, 'en', "child").
ontology_label('http://fogid.net/o/mother', inverse, 'ru', "ребенок").
ontology_label('http://fogid.net/o/name', forward, 'en', "name").
ontology_label('http://fogid.net/o/name', forward, 'ru', "имя").
ontology_label('http://fogid.net/o/naming', forward, 'en', "Naming").
ontology_label('http://fogid.net/o/naming', forward, 'ru', "Именование").
ontology_label('http://fogid.net/o/org-category', forward, 'en', "organization form").
ontology_label('http://fogid.net/o/org-category', forward, 'ru', "вид.орг.").
ontology_label('http://fogid.net/o/org-child', forward, 'en', "child organization").
ontology_label('http://fogid.net/o/org-child', forward, 'ru', "орг.ребенок").
ontology_label('http://fogid.net/o/org-child', inverse, 'en', "child organization for").
ontology_label('http://fogid.net/o/org-child', inverse, 'ru', "орг.ребенок для").
ontology_label('http://fogid.net/o/org-classification', forward, 'en', "organization classifier").
ontology_label('http://fogid.net/o/org-classification', forward, 'ru', "классификатор орг.").
ontology_label('http://fogid.net/o/org-parent', forward, 'en', "parent organization").
ontology_label('http://fogid.net/o/org-parent', forward, 'ru', "орг.родитель").
ontology_label('http://fogid.net/o/org-parent', inverse, 'en', "parent organization for").
ontology_label('http://fogid.net/o/org-parent', inverse, 'ru', "орг.родитель для").
ontology_label('http://fogid.net/o/org-relatives', forward, 'en', "Related organizations").
ontology_label('http://fogid.net/o/org-relatives', forward, 'ru', "Родственные организации").
ontology_label('http://fogid.net/o/org-sys', forward, 'en', "Organization system").
ontology_label('http://fogid.net/o/org-sys', forward, 'ru', "Организационная система").
ontology_label('http://fogid.net/o/pageNumbers', forward, 'en', "page numbers").
ontology_label('http://fogid.net/o/pageNumbers', forward, 'ru', "номера страниц").
ontology_label('http://fogid.net/o/partItem', forward, 'en', "part of document").
ontology_label('http://fogid.net/o/partItem', forward, 'ru', "часть документа").
ontology_label('http://fogid.net/o/partItem', inverse, 'en', "is a part").
ontology_label('http://fogid.net/o/partItem', inverse, 'ru', "является частью").
ontology_label('http://fogid.net/o/participant', forward, 'en', "participant").
ontology_label('http://fogid.net/o/participant', forward, 'ru', "участник").
ontology_label('http://fogid.net/o/participant', inverse, 'en', "participant in organization").
ontology_label('http://fogid.net/o/participant', inverse, 'ru', "участник в орг.").
ontology_label('http://fogid.net/o/participation', forward, 'en', "Participation").
ontology_label('http://fogid.net/o/participation', forward, 'ru', "Участие").
ontology_label('http://fogid.net/o/person', forward, 'en', "Person").
ontology_label('http://fogid.net/o/person', forward, 'ru', "Персона").
ontology_label('http://fogid.net/o/photo-doc', forward, 'en', "Photo document").
ontology_label('http://fogid.net/o/photo-doc', forward, 'ru', "Фотодокумент").
ontology_label('http://fogid.net/o/pupil', forward, 'en', "Schoolchild").
ontology_label('http://fogid.net/o/pupil', forward, 'ru', "Школьник").
ontology_label('http://fogid.net/o/referred', forward, 'en', "by date").
ontology_label('http://fogid.net/o/referred', forward, 'ru', "датируемое").
ontology_label('http://fogid.net/o/referred', inverse, 'en', "is dated").
ontology_label('http://fogid.net/o/referred', inverse, 'ru', "датируется").
ontology_label('http://fogid.net/o/referred-sys', forward, 'en', "by name").
ontology_label('http://fogid.net/o/referred-sys', forward, 'ru', "именуемое").
ontology_label('http://fogid.net/o/referred-sys', inverse, 'en', "beeing called").
ontology_label('http://fogid.net/o/referred-sys', inverse, 'ru', "именуется").
ontology_label('http://fogid.net/o/reflected', forward, 'en', "reflected item").
ontology_label('http://fogid.net/o/reflected', forward, 'ru', "отражаемое").
ontology_label('http://fogid.net/o/reflected', inverse, 'en', "reflected in document").
ontology_label('http://fogid.net/o/reflected', inverse, 'ru', "отраж. в документе").
ontology_label('http://fogid.net/o/reflection', forward, 'en', "Reflection").
ontology_label('http://fogid.net/o/reflection', forward, 'ru', "Отражение").
ontology_label('http://fogid.net/o/region', forward, 'en', "Region").
ontology_label('http://fogid.net/o/region', forward, 'ru', "Регион").
ontology_label('http://fogid.net/o/role', forward, 'en', "role").
ontology_label('http://fogid.net/o/role', forward, 'ru', "роль").
ontology_label('http://fogid.net/o/role-classification', forward, 'en', "role classifier").
ontology_label('http://fogid.net/o/role-classification', forward, 'ru', "клсф.роли").
ontology_label('http://fogid.net/o/sex', forward, 'en', "sex").
ontology_label('http://fogid.net/o/sex', forward, 'ru', "пол").
ontology_label('http://fogid.net/o/something', forward, 'en', "settable").
ontology_label('http://fogid.net/o/something', forward, 'ru', "размещаемое").
ontology_label('http://fogid.net/o/something', inverse, 'en', "located in").
ontology_label('http://fogid.net/o/something', inverse, 'ru', "находится в").
ontology_label('http://fogid.net/o/speech', forward, 'en', "Speech").
ontology_label('http://fogid.net/o/speech', forward, 'ru', "Выступление").
ontology_label('http://fogid.net/o/student', forward, 'en', "Student").
ontology_label('http://fogid.net/o/student', forward, 'ru', "Студент").
ontology_label('http://fogid.net/o/support-org', forward, 'en', "supporting organization").
ontology_label('http://fogid.net/o/support-org', forward, 'ru', "поддерж. орг.").
ontology_label('http://fogid.net/o/support-org', inverse, 'en', "supports").
ontology_label('http://fogid.net/o/support-org', inverse, 'ru', "поддерживает").
ontology_label('http://fogid.net/o/titled', forward, 'en', "Entitled").
ontology_label('http://fogid.net/o/titled', forward, 'ru', "Титулован").
ontology_label('http://fogid.net/o/to-date', forward, 'en', "final date").
ontology_label('http://fogid.net/o/to-date', forward, 'ru', "кон.дата").
ontology_label('http://fogid.net/o/uri', forward, 'en', "published in").
ontology_label('http://fogid.net/o/uri', forward, 'ru', "опубликован в").
ontology_label('http://fogid.net/o/user', forward, 'en', "user").
ontology_label('http://fogid.net/o/user', forward, 'ru', "абонент").
ontology_label('http://fogid.net/o/user', inverse, 'en', "user").
ontology_label('http://fogid.net/o/user', inverse, 'ru', "абонент").
ontology_label('http://fogid.net/o/video-doc', forward, 'en', "Video document").
ontology_label('http://fogid.net/o/video-doc', forward, 'ru', "Видеодокумент").
ontology_label('http://fogid.net/o/wife', forward, 'en', "wife").
ontology_label('http://fogid.net/o/wife', forward, 'ru', "жена").
ontology_label('http://fogid.net/o/wife', inverse, 'en', "wife for").
ontology_label('http://fogid.net/o/wife', inverse, 'ru', "жена для").

ontology_priority('http://fogid.net/o/adoc', "m").
ontology_priority('http://fogid.net/o/alias', "n").
ontology_priority('http://fogid.net/o/archive-item', "a").
ontology_priority('http://fogid.net/o/author', "n").
ontology_priority('http://fogid.net/o/business', "n").
ontology_priority('http://fogid.net/o/code', "n").
ontology_priority('http://fogid.net/o/collection-item', "a").
ontology_priority('http://fogid.net/o/comment', "z").
ontology_priority('http://fogid.net/o/date', "n").
ontology_priority('http://fogid.net/o/degree', "n").
ontology_priority('http://fogid.net/o/description', "s").
ontology_priority('http://fogid.net/o/doc-content', "u").
ontology_priority('http://fogid.net/o/docmetainfo', "d").
ontology_priority('http://fogid.net/o/father', "t").
ontology_priority('http://fogid.net/o/from-date', "r").
ontology_priority('http://fogid.net/o/geosys-category', "ac").
ontology_priority('http://fogid.net/o/ground', "o").
ontology_priority('http://fogid.net/o/has-activity', "m").
ontology_priority('http://fogid.net/o/has-title', "m").
ontology_priority('http://fogid.net/o/husband', "m").
ontology_priority('http://fogid.net/o/in-archive', "a").
ontology_priority('http://fogid.net/o/in-collection', "a").
ontology_priority('http://fogid.net/o/in-doc', "a").
ontology_priority('http://fogid.net/o/in-org', "n").
ontology_priority('http://fogid.net/o/inDocument', "m").
ontology_priority('http://fogid.net/o/learn-category', "o").
ontology_priority('http://fogid.net/o/learner', "m").
ontology_priority('http://fogid.net/o/learning-org', "n").
ontology_priority('http://fogid.net/o/location-category', "o").
ontology_priority('http://fogid.net/o/location-classification', "o").
ontology_priority('http://fogid.net/o/location-place', "n").
ontology_priority('http://fogid.net/o/mother', "t").
ontology_priority('http://fogid.net/o/name', "a").
ontology_priority('http://fogid.net/o/org-category', "ac").
ontology_priority('http://fogid.net/o/org-child', "n").
ontology_priority('http://fogid.net/o/org-classification', "ab").
ontology_priority('http://fogid.net/o/org-parent', "m").
ontology_priority('http://fogid.net/o/partItem', "m").
ontology_priority('http://fogid.net/o/participant', "m").
ontology_priority('http://fogid.net/o/referred', "m").
ontology_priority('http://fogid.net/o/referred-sys', "m").
ontology_priority('http://fogid.net/o/reflected', "a").
ontology_priority('http://fogid.net/o/role', "o").
ontology_priority('http://fogid.net/o/role-classification', "o").
ontology_priority('http://fogid.net/o/sex', "u").
ontology_priority('http://fogid.net/o/something', "m").
ontology_priority('http://fogid.net/o/support-org', "o").
ontology_priority('http://fogid.net/o/to-date', "t").
ontology_priority('http://fogid.net/o/uri', "c").
ontology_priority('http://fogid.net/o/user', "m").
ontology_priority('http://fogid.net/o/wife', "n").
