using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using LogicLens.Core.Graph;
using LogicLens.Core.Model;
using LogicLens.Prolog.Serialization;

namespace LogicLens.Prolog.Epoch;

public sealed record GeneratedEpochFile(
    string RelativePath,
    string Content,
    string Sha256);

public sealed record PrologEpochPackage(
    int Epoch,
    string CompilerCommit,
    int FactCount,
    int OriginCount,
    string DataHash,
    IReadOnlyList<GeneratedEpochFile> Files,
    string ManifestJson);

public sealed class PrologEpochWriter
{
    private const string FactsPath = "data/facts.generated.pl";
    private const string OriginsPath = "data/origins.generated.pl";
    private static readonly UTF8Encoding Utf8WithoutBom = new(false);

    public PrologEpochPackage Build(
        CanonicalGraph graph,
        int epoch,
        string compilerCommit)
    {
        ArgumentNullException.ThrowIfNull(graph);
        if (epoch < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(epoch));
        }

        if (string.IsNullOrWhiteSpace(compilerCommit))
        {
            throw new ArgumentException(
                "Compiler commit cannot be null, empty, or whitespace.",
                nameof(compilerCommit));
        }

        var factsContent = BuildFacts(graph);
        var origins = CollectOrigins(graph);
        var originsContent = BuildOrigins(graph, origins);

        var files = new[]
        {
            CreateFile(FactsPath, factsContent),
            CreateFile(OriginsPath, originsContent)
        };
        var dataHash = ComputeDataHash(files);
        var manifestJson = BuildManifest(
            epoch,
            compilerCommit,
            graph.Count,
            origins.Count,
            files,
            dataHash);

        return new PrologEpochPackage(
            epoch,
            compilerCommit,
            graph.Count,
            origins.Count,
            dataHash,
            files,
            manifestJson);
    }

    public void WriteToDirectory(
        PrologEpochPackage package,
        string outputDirectory)
    {
        ArgumentNullException.ThrowIfNull(package);
        if (string.IsNullOrWhiteSpace(outputDirectory))
        {
            throw new ArgumentException(
                "Output directory cannot be null, empty, or whitespace.",
                nameof(outputDirectory));
        }

        Directory.CreateDirectory(outputDirectory);

        foreach (var file in package.Files)
        {
            var path = ResolveOutputPath(outputDirectory, file.RelativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(path)
                ?? throw new InvalidOperationException($"No directory for '{path}'."));
            File.WriteAllText(path, file.Content, Utf8WithoutBom);
        }

        File.WriteAllText(
            ResolveOutputPath(outputDirectory, "manifest.json"),
            package.ManifestJson,
            Utf8WithoutBom);
    }

    private static string BuildFacts(CanonicalGraph graph)
    {
        var builder = new StringBuilder();
        builder.AppendLine("% Generated by LogicLens Prolog data contract v1. Do not edit.");

        foreach (var entry in graph.Entries
                     .OrderBy(static item => item.Fact.FactId, StringComparer.Ordinal))
        {
            var fact = entry.Fact;
            builder
                .Append("fact(")
                .Append(PrologText.Atom(fact.FactId)).Append(", ")
                .Append(PrologText.Atom(fact.Subject)).Append(", ")
                .Append(PrologText.Atom(fact.Predicate)).Append(", ")
                .Append(RenderObject(fact.Object))
                .AppendLine(").");
        }

        return NormalizeTrailingLineFeed(builder);
    }

    private static string BuildOrigins(
        CanonicalGraph graph,
        IReadOnlyDictionary<string, Origin> origins)
    {
        var builder = new StringBuilder();
        builder.AppendLine("% Generated by LogicLens Prolog data contract v1. Do not edit.");

        foreach (var origin in origins.Values
                     .OrderBy(static item => item.OriginId, StringComparer.Ordinal))
        {
            builder
                .Append("origin(")
                .Append(PrologText.Atom(origin.OriginId)).Append(", archival(")
                .Append(PrologText.String(origin.SourcePath)).Append(", ")
                .Append(PrologText.String(origin.SourceDbId)).Append(", ")
                .Append(PrologText.Atom(origin.EntityId))
                .AppendLine(")).");
        }

        builder.AppendLine();

        foreach (var pair in graph.Entries
                     .SelectMany(static entry => entry.Origins.Select(origin =>
                         (entry.Fact.FactId, origin.OriginId)))
                     .OrderBy(static pair => pair.FactId, StringComparer.Ordinal)
                     .ThenBy(static pair => pair.OriginId, StringComparer.Ordinal))
        {
            builder
                .Append("fact_origin(")
                .Append(PrologText.Atom(pair.FactId)).Append(", ")
                .Append(PrologText.Atom(pair.OriginId))
                .AppendLine(").");
        }

        return NormalizeTrailingLineFeed(builder);
    }

    private static IReadOnlyDictionary<string, Origin> CollectOrigins(CanonicalGraph graph)
    {
        var result = new Dictionary<string, Origin>(StringComparer.Ordinal);

        foreach (var origin in graph.Entries.SelectMany(static entry => entry.Origins))
        {
            if (result.TryGetValue(origin.OriginId, out var existing))
            {
                if (existing != origin)
                {
                    throw new InvalidOperationException(
                        $"OriginId '{origin.OriginId}' has conflicting metadata.");
                }

                continue;
            }

            result.Add(origin.OriginId, origin);
        }

        return result;
    }

    private static string RenderObject(FactObject value) => value switch
    {
        IriObject iri => $"iri({PrologText.Atom(iri.Value)})",
        LiteralObject { Kind: LiteralKind.Plain } literal =>
            $"literal({PrologText.String(literal.Lexical)}, plain)",
        LiteralObject { Kind: LiteralKind.Language } literal =>
            $"literal({PrologText.String(literal.Lexical)}, " +
            $"lang({PrologText.Atom(literal.Language
                ?? throw new InvalidOperationException("Language tag is missing."))}))",
        LiteralObject { Kind: LiteralKind.Datatype } literal =>
            $"literal({PrologText.String(literal.Lexical)}, " +
            $"datatype({PrologText.Atom(literal.Datatype
                ?? throw new InvalidOperationException("Datatype IRI is missing."))}))",
        _ => throw new ArgumentOutOfRangeException(
            nameof(value),
            value,
            "Unsupported canonical fact object.")
    };

    private static GeneratedEpochFile CreateFile(string path, string content)
    {
        var bytes = Utf8WithoutBom.GetBytes(content);
        return new GeneratedEpochFile(path, content, Sha256(bytes));
    }

    private static string ComputeDataHash(IReadOnlyList<GeneratedEpochFile> files)
    {
        using var hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
        hash.AppendData(Encoding.ASCII.GetBytes("LogicLensPrologData\0"));
        hash.AppendData([0x01]);

        foreach (var file in files.OrderBy(
                     static item => item.RelativePath,
                     StringComparer.Ordinal))
        {
            AppendField(hash, Encoding.UTF8.GetBytes(file.RelativePath));
            AppendField(hash, Utf8WithoutBom.GetBytes(file.Content));
        }

        return "sha256:" + Convert.ToHexString(hash.GetHashAndReset()).ToLowerInvariant();
    }

    private static string BuildManifest(
        int epoch,
        string compilerCommit,
        int factCount,
        int originCount,
        IReadOnlyList<GeneratedEpochFile> files,
        string dataHash)
    {
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream, new JsonWriterOptions
               {
                   Indented = true
               }))
        {
            writer.WriteStartObject();
            writer.WriteNumber("epoch", epoch);
            writer.WriteString("stage", "data-generated");
            writer.WriteString("factContractVersion", "1");
            writer.WriteNumber("factIdEncodingVersion", 1);
            writer.WriteString("prologDataContractVersion", "1");
            writer.WriteString("compilerCommit", compilerCommit);
            writer.WriteNumber("factCount", factCount);
            writer.WriteNumber("originCount", originCount);
            writer.WriteStartObject("files");
            foreach (var file in files.OrderBy(
                         static item => item.RelativePath,
                         StringComparer.Ordinal))
            {
                writer.WriteString(file.RelativePath, file.Sha256);
            }

            writer.WriteEndObject();
            writer.WriteString("dataHash", dataHash);
            writer.WriteEndObject();
        }

        return Utf8WithoutBom.GetString(stream.ToArray()) + "\n";
    }

    private static void AppendField(IncrementalHash hash, byte[] bytes)
    {
        Span<byte> length = stackalloc byte[sizeof(ulong)];
        BinaryPrimitives.WriteUInt64BigEndian(length, checked((ulong)bytes.Length));
        hash.AppendData(length);
        hash.AppendData(bytes);
    }

    private static string NormalizeTrailingLineFeed(StringBuilder builder) =>
        builder.ToString().TrimEnd('\r', '\n') + "\n";

    private static string Sha256(byte[] bytes) =>
        "sha256:" + Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();

    private static string ResolveOutputPath(string outputDirectory, string relativePath)
    {
        var root = Path.GetFullPath(outputDirectory);
        var path = Path.GetFullPath(Path.Combine(
            root,
            relativePath.Replace('/', Path.DirectorySeparatorChar)));
        var rootWithSeparator = root.EndsWith(Path.DirectorySeparatorChar)
            ? root
            : root + Path.DirectorySeparatorChar;

        if (!path.StartsWith(rootWithSeparator, StringComparison.Ordinal)
            && !StringComparer.Ordinal.Equals(path, root))
        {
            throw new InvalidOperationException(
                $"Generated path escapes output directory: '{relativePath}'.");
        }

        return path;
    }
}
